# Generated by Django 5.2.14 on 2026-06-01 07:04

import apps.common.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag label.", max_length=50, unique=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex colour code for UI display, e.g. '#3B82F6'.",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                ("name", models.CharField(help_text="Category name.", max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly slug for the category.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of this category.",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category for hierarchy.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="documents.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID for API access.",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Document title.", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional document description.",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded document file.",
                        upload_to=apps.common.utils.generate_upload_path,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("doc", "Word (doc)"),
                            ("docx", "Word (docx)"),
                            ("txt", "Plain Text"),
                            ("png", "PNG Image"),
                            ("jpg", "JPEG Image"),
                            ("jpeg", "JPEG Image"),
                            ("xlsx", "Excel"),
                            ("csv", "CSV"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of the uploaded file.",
                        max_length=10,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="File size in bytes."),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Physical storage path of the current file.",
                        max_length=500,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Original filename as uploaded by the user.",
                        max_length=255,
                    ),
                ),
                (
                    "current_version",
                    models.PositiveIntegerField(
                        default=1, help_text="Current version number."
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Whether the document is archived."
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="Soft-delete flag."),
                ),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("n/a", "Not Applicable"),
                        ],
                        default="pending",
                        help_text="Status of OCR processing.",
                        max_length=20,
                    ),
                ),
                (
                    "ai_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Status of AI processing (summarisation, embeddings).",
                        max_length=20,
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full text extracted from the document (via OCR or parsing).",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category this document belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.category",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns this document.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_tags",
                        to="documents.document",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="The tag.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_tags",
                        to="documents.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Tag",
                "verbose_name_plural": "Document Tags",
                "db_table": "document_tags",
                "unique_together": {("document", "tag")},
            },
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags associated with this document.",
                related_name="documents",
                through="documents.DocumentTag",
                to="documents.tag",
            ),
        ),
        migrations.CreateModel(
            name="DocumentAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer"),
                            ("editor", "Editor"),
                            ("admin", "Admin"),
                        ],
                        default="viewer",
                        help_text="Level of access granted.",
                        max_length=10,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document being shared.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_records",
                        to="documents.document",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who granted this access.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who has access.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Access",
                "verbose_name_plural": "Document Access",
                "db_table": "document_access",
                "unique_together": {("document", "user")},
            },
        ),
        migrations.CreateModel(
            name="DocumentMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Metadata key, e.g. 'author', 'page_count'.",
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Metadata value (stored as text, interpret via value_type)."
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        help_text="Data type hint for the value.",
                        max_length=10,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Document this metadata belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Metadata",
                "verbose_name_plural": "Document Metadata",
                "db_table": "document_metadata",
                "unique_together": {("document", "key")},
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(help_text="Sequential version number."),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="File for this specific version.",
                        upload_to="versions/",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Storage path for this version's file.",
                        max_length=500,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="File size in bytes."),
                ),
                (
                    "change_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of changes in this version.",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 checksum of the file.",
                        max_length=128,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document this version belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded this version.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Version",
                "verbose_name_plural": "Document Versions",
                "db_table": "document_versions",
                "ordering": ["-version_number"],
                "unique_together": {("document", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["uuid"], name="documents_uuid_1d767f_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["owner", "-created_at"], name="documents_owner_i_9f8226_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["file_type"], name="documents_file_ty_4b3ae1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_archived", "is_deleted"],
                name="documents_is_arch_519c09_idx",
            ),
        ),
    ]
