# Generated by Django 5.2.14 on 2026-06-01 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        help_text="The search query string.", max_length=500
                    ),
                ),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("fulltext", "Full-Text"),
                            ("semantic", "Semantic"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="fulltext",
                        help_text="Type of search performed.",
                        max_length=20,
                    ),
                ),
                (
                    "results_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of results returned."
                    ),
                ),
                (
                    "filters_applied",
                    models.JSONField(
                        blank=True,
                        help_text="Filters applied during the search (JSON).",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the search.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search History",
                "verbose_name_plural": "Search History",
                "db_table": "search_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-defined name for the saved search.",
                        max_length=100,
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        help_text="The search query string.", max_length=500
                    ),
                ),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("fulltext", "Full-Text"),
                            ("semantic", "Semantic"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="fulltext",
                        max_length=20,
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        help_text="Saved filter parameters (JSON).",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who saved the search.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Search",
                "verbose_name_plural": "Saved Searches",
                "db_table": "saved_searches",
                "ordering": ["-created_at"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
